/// <reference types="react" />
/// <reference types="react" />
declare const Select: import("styled-components").IStyledComponent<"web", {
    ref?: import("react").LegacyRef<HTMLSelectElement> | undefined;
    key?: import("react").Key | null | undefined;
    autoComplete?: string | undefined;
    disabled?: boolean | undefined;
    form?: string | undefined;
    multiple?: boolean | undefined;
    name?: string | undefined;
    required?: boolean | undefined;
    size?: number | undefined;
    value?: string | number | readonly string[] | undefined;
    onChange?: import("react").ChangeEventHandler<HTMLSelectElement> | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    className?: string | undefined;
    contentEditable?: (boolean | "true" | "false") | "inherit" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "true" | "false") | undefined;
    hidden?: boolean | undefined;
    id?: string | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    placeholder?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "true" | "false") | undefined;
    style?: import("react").CSSProperties | undefined;
    tabIndex?: number | undefined;
    title?: string | undefined;
    translate?: "yes" | "no" | undefined;
    radioGroup?: string | undefined;
    role?: import("react").AriaRole | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    color?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "text" | "search" | "none" | "tel" | "url" | "email" | "numeric" | "decimal" | undefined;
    is?: string | undefined;
    'aria-activedescendant'?: string | undefined;
    'aria-atomic'?: (boolean | "true" | "false") | undefined;
    'aria-autocomplete'?: "list" | "none" | "inline" | "both" | undefined;
    'aria-braillelabel'?: string | undefined;
    'aria-brailleroledescription'?: string | undefined;
    'aria-busy'?: (boolean | "true" | "false") | undefined;
    'aria-checked'?: boolean | "true" | "false" | "mixed" | undefined;
    'aria-colcount'?: number | undefined;
    'aria-colindex'?: number | undefined;
    'aria-colindextext'?: string | undefined;
    'aria-colspan'?: number | undefined;
    'aria-controls'?: string | undefined;
    'aria-current'?: boolean | "time" | "step" | "true" | "false" | "page" | "location" | "date" | undefined;
    'aria-describedby'?: string | undefined;
    'aria-description'?: string | undefined;
    'aria-details'?: string | undefined;
    'aria-disabled'?: (boolean | "true" | "false") | undefined;
    'aria-dropeffect'?: "link" | "none" | "copy" | "execute" | "move" | "popup" | undefined;
    'aria-errormessage'?: string | undefined;
    'aria-expanded'?: (boolean | "true" | "false") | undefined;
    'aria-flowto'?: string | undefined;
    'aria-grabbed'?: (boolean | "true" | "false") | undefined;
    'aria-haspopup'?: boolean | "dialog" | "menu" | "true" | "false" | "grid" | "listbox" | "tree" | undefined;
    'aria-hidden'?: (boolean | "true" | "false") | undefined;
    'aria-invalid'?: boolean | "true" | "false" | "grammar" | "spelling" | undefined;
    'aria-keyshortcuts'?: string | undefined;
    'aria-label'?: string | undefined;
    'aria-labelledby'?: string | undefined;
    'aria-level'?: number | undefined;
    'aria-live'?: "off" | "assertive" | "polite" | undefined;
    'aria-modal'?: (boolean | "true" | "false") | undefined;
    'aria-multiline'?: (boolean | "true" | "false") | undefined;
    'aria-multiselectable'?: (boolean | "true" | "false") | undefined;
    'aria-orientation'?: "horizontal" | "vertical" | undefined;
    'aria-owns'?: string | undefined;
    'aria-placeholder'?: string | undefined;
    'aria-posinset'?: number | undefined;
    'aria-pressed'?: boolean | "true" | "false" | "mixed" | undefined;
    'aria-readonly'?: (boolean | "true" | "false") | undefined;
    'aria-relevant'?: "text" | "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    'aria-required'?: (boolean | "true" | "false") | undefined;
    'aria-roledescription'?: string | undefined;
    'aria-rowcount'?: number | undefined;
    'aria-rowindex'?: number | undefined;
    'aria-rowindextext'?: string | undefined;
    'aria-rowspan'?: number | undefined;
    'aria-selected'?: (boolean | "true" | "false") | undefined;
    'aria-setsize'?: number | undefined;
    'aria-sort'?: "none" | "ascending" | "descending" | "other" | undefined;
    'aria-valuemax'?: number | undefined;
    'aria-valuemin'?: number | undefined;
    'aria-valuenow'?: number | undefined;
    'aria-valuetext'?: string | undefined;
    children?: import("react").ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import("react").ClipboardEventHandler<HTMLSelectElement> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<HTMLSelectElement> | undefined;
    onCut?: import("react").ClipboardEventHandler<HTMLSelectElement> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<HTMLSelectElement> | undefined;
    onPaste?: import("react").ClipboardEventHandler<HTMLSelectElement> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<HTMLSelectElement> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<HTMLSelectElement> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<HTMLSelectElement> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<HTMLSelectElement> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<HTMLSelectElement> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<HTMLSelectElement> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<HTMLSelectElement> | undefined;
    onFocus?: import("react").FocusEventHandler<HTMLSelectElement> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<HTMLSelectElement> | undefined;
    onBlur?: import("react").FocusEventHandler<HTMLSelectElement> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<HTMLSelectElement> | undefined;
    onChangeCapture?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onBeforeInput?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onInput?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onInputCapture?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onReset?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onResetCapture?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onSubmit?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onInvalid?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<HTMLSelectElement> | undefined;
    onLoad?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onError?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<HTMLSelectElement> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<HTMLSelectElement> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<HTMLSelectElement> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<HTMLSelectElement> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<HTMLSelectElement> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<HTMLSelectElement> | undefined;
    onAbort?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onCanPlay?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onDurationChange?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onEmptied?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onEncrypted?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onEnded?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onLoadedData?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onLoadStart?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onPause?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onPlay?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onPlaying?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onProgress?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onRateChange?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onResize?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onResizeCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onSeeked?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onSeeking?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onStalled?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onSuspend?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onWaiting?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onAuxClick?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onClick?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onClickCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onContextMenu?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onDrag?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragEnd?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragEnter?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragExit?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragLeave?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragOver?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragStart?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDrop?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onDropCapture?: import("react").DragEventHandler<HTMLSelectElement> | undefined;
    onMouseDown?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseEnter?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseLeave?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseMove?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseOut?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseOver?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseUp?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<HTMLSelectElement> | undefined;
    onSelect?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<HTMLSelectElement> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onTouchMove?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onTouchStart?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<HTMLSelectElement> | undefined;
    onPointerDown?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerMove?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerUp?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerEnterCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerLeaveCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerOver?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerOut?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<HTMLSelectElement> | undefined;
    onScroll?: import("react").UIEventHandler<HTMLSelectElement> | undefined;
    onScrollCapture?: import("react").UIEventHandler<HTMLSelectElement> | undefined;
    onWheel?: import("react").WheelEventHandler<HTMLSelectElement> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<HTMLSelectElement> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<HTMLSelectElement> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<HTMLSelectElement> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<HTMLSelectElement> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<HTMLSelectElement> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<HTMLSelectElement> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<HTMLSelectElement> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<HTMLSelectElement> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<HTMLSelectElement> | undefined;
}>;
export default Select;
